# -*- coding: utf-8 -*-
"""spleeter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/deezer/spleeter/blob/master/spleeter.ipynb

# Install spleeter
"""

!apt install ffmpeg

pip install spleeter

from IPython.display import Audio

"""# Separate from command line"""

!wget https://github.com/deezer/spleeter/raw/master/audio_example.mp3

Audio('audio_example.mp3')

!spleeter separate -h

!spleeter separate -o output/ audio_example.mp3

!ls output/audio_example

Audio('output/audio_example/vocals.wav')

Audio('output/audio_example/accompaniment.wav')